name: push-gh-pages
run-name: ${{ github.actor }} is pushing gh-pages
on:
  release:
    types: [published]

jobs:
  push-gh-pages:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
      VERSION: ${TAG_NAME#v}
    steps:
      - uses: actions/checkout@v3
      - name: Setup git user
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name: Create push directory
        run: |
          mkdir gh-pages
          git init -b gh-pages ./gh-pages
          cd ./gh-pages
          git remoate add -t gh-pages origin \
          https://git:${{ github.token }}@github.com/${{ github.repository }}.git
          git pull origin gh-pages
          cd ..
      - name: Create publish version ${ VERSION }
        run: |
          rm -rf ./gh-pages/${ VERSION }
          cp -rf ./src/* ./gh-pages/${ VERSION }/
      - name: Push to gh-pages
        run: |
          cd ./gh-pages
          git add .
          git commit -m "${{ github.actor }} publis version ${ VERSION }"
          git push orgin gh-pages
